### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-runtime"

### ISSUE THREAD

**Issue by olafdunn** [adonisjs/adonis-blog-demo#6]
When running `npm run build:dev` the following is output:
```
> adonis-blog-demo@4.0.0 build:dev /Users/xxxx/Sites/adonis-blog-demo
> cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                      

 ERROR  Failed to compile with 1 errors                                                                                                                              13:26:28

 error  in ./resources/assets/js/app.js

Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/xxxx/.babelrc" at 0, attempted to resolve relative to "/Users/xxxx"
    at /Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)

 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

             Asset    Size  Chunks             Chunk Names
 /public/js/app.js  4.3 kB       0  [emitted]  /public/js/app
public/css/app.css  178 kB       0  [emitted]  /public/js/app

ERROR in ./resources/assets/js/app.js
Module build failed: ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/xxxx/.babelrc" at 0, attempted to resolve relative to "/Users/xxxx"
    at /Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/xxxx/Sites/adonis-blog-demo/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! adonis-blog-demo@4.0.0 build:dev: `cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the adonis-blog-demo@4.0.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxx/.npm/_logs/2017-11-27T18_26_28_548Z-debug.log
```

**Comment by RomainLanz** [comment]
Hey @olafdunn! 👋 

Have you tried to delete all node modules and reinstall them?

**Comment by olafdunn** [comment]
I tried removing the node_modules directory, and running `npm install` again. However I still get the same issues.

There are however some errors thrown during npm install. Are these expected?

```
> node-sass@4.5.3 install /Users/xxxx/Sites/adonis-blog-demo/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/darwin-x64-59_binding.node": 

HTTP error 404 Not Found
```

.....

```
> sqlite3@3.1.13 install /Users/xxxx/Sites/adonis-blog-demo/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.13/node-v59-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.13 and node@9.2.0 (node-v59 ABI) (falling back to source compile with node-gyp) 
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3150000/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3150000/sqlite3.o
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
In file included from ../src/database.cc:4:
In file included from ../src/database.h:10:
In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/xxxx/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
../src/database.cc:144:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:525:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:625:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
5 warnings generated.
  CXX(target) Release/obj.target/node_sqlite3/src/node_sqlite3.o
In file included from ../src/node_sqlite3.cc:8:
In file included from ../src/database.h:10:
In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/xxxx/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
1 warning generated.
  CXX(target) Release/obj.target/node_sqlite3/src/statement.o
In file included from ../src/statement.cc:7:
In file included from ../src/database.h:10:
In file included from ../node_modules/nan/nan.h:192:
../node_modules/nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/xxxx/.node-gyp/9.2.0/include/node/v8.h:3115:29: note: 'ForceSet' has been explicitly marked deprecated here
                Maybe<bool> ForceSet(Local<Context> context, Local<Value> key,
                            ^
../src/statement.cc:118:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/statement.cc:322:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Bind);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:370:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Get);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:438:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Run);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:504:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(All);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:601:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Each);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
../src/statement.cc:724:5: warning: unused variable 'status' [-Wunused-variable]
    STATEMENT_BEGIN(Reset);
    ^
../src/macros.h:125:9: note: expanded from macro 'STATEMENT_BEGIN'
    int status = uv_queue_work(uv_default_loop(),                              \
        ^
8 warnings generated.
  SOLINK_MODULE(target) Release/node_sqlite3.node
  COPY /Users/xxxx/Sites/adonis-blog-demo/node_modules/sqlite3/lib/binding/node-v59-darwin-x64/node_sqlite3.node
  TOUCH Release/obj.target/action_after_build.stamp
```

....

**Comment by thetutlage** [comment]
I am the dirties thing about transpilers, that's why I always kept Adonis away from them.

**Comment by thetutlage** [comment]
Can u please share the OS and Node version you are on?
